version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.4
    working_directory: /go/src/github.com/robinjoseph08/hello
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src/github.com/robinjoseph08/hello/.git
      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.lock" }}
      - run:
          name: Setup project
          command: make setup
      - run:
          name: Install dependencies
          command: dep ensure -vendor-only
      - save_cache:
          key: vendor-{{ checksum "Gopkg.lock" }}
          paths:
            - ~/.cache/go-build
            - /go/src/github.com/robinjoseph08/hello/vendor
      - run:
          name: Run linter
          command: make lint
      - run:
          name: Run tests
          command: make test
